name: core_of_perception
description: The core API for perception principles and peripherals.
version: 0.0.0-a1
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  meta: ^1.9.1
  
  error_handling_for_perception: ^0.0.0-a1
  locator_for_perception: ^0.0.0-a1
  types_for_perception: ^0.0.0-a1

  json_utils: ^0.0.0-a1

dev_dependencies:
  flutter_test:
    sdk: flutter
  enspyr_lints: ^0.0.0-a1
